# Generated by Django 3.2.6 on 2021-08-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tour_type', models.CharField(choices=[('i', 'Island'), ('g', 'Georgia'), ('s', 'Swamp'), ('f', 'Float')], max_length=1)),
                ('description', models.TextField()),
                ('cost', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('vacant_spot', models.IntegerField()),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_numbers', models.IntegerField(default=1)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vtur.tour')),
            ],
        ),
    ]
