# Generated by Django 3.2.6 on 2021-08-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vtur', '0003_tour_booker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='booker',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
