# Generated by Django 3.2.6 on 2021-08-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vtur', '0004_auto_20210808_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='program',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
