# Generated by Django 3.2.6 on 2021-08-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vtur', '0005_tour_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
